name: Deploy Storage Account

on:
  push:
    branches:
      - prod

permissions:
  id-token: write 
  contents: read    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Storage Account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage account create --name wweweqwe323 --resource-group AZ-something --location EastUS2 --sku Standard_LRS